// <auto-generated />
using System;
using Biblioteca.Modelo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Biblioteca.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    [Migration("20220623020107_inicio1")]
    partial class inicio1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Biblioteca.Modelo.Lector", b =>
                {
                    b.Property<int>("lectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lectorId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnName("Apellido")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Domicilio")
                        .HasColumnName("Domicilio")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Localidad")
                        .HasColumnName("Localidad")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("Nombre")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<int>("Provincia")
                        .HasColumnName("Provincia")
                        .HasColumnType("int");

                    b.HasKey("lectorId");

                    b.ToTable("lectores");
                });

            modelBuilder.Entity("Biblioteca.Modelo.Libro", b =>
                {
                    b.Property<int>("libroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("libroId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("edicion")
                        .HasColumnName("edicion")
                        .HasColumnType("int");

                    b.Property<string>("rutaimagen")
                        .HasColumnName("rutaimagen")
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("titulo")
                        .HasColumnName("titulo")
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.HasKey("libroId");

                    b.ToTable("libros");
                });

            modelBuilder.Entity("Biblioteca.Modelo.Prestamo", b =>
                {
                    b.Property<int>("prestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Lector")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Libro")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Usuario")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<bool>("devolucion")
                        .HasColumnName("devolucion")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaHora")
                        .HasColumnName("FechaHora")
                        .HasColumnType("datetime2");

                    b.HasKey("prestamoId");

                    b.HasIndex("Lector");

                    b.HasIndex("Libro");

                    b.HasIndex("Usuario");

                    b.ToTable("prestamos");
                });

            modelBuilder.Entity("Biblioteca.Modelo.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("usuarioId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnName("Apellido")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Domicilio")
                        .HasColumnName("Domicilio")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Localidad")
                        .HasColumnName("Localidad")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nombre")
                        .HasColumnName("Nombre")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<int>("Provincia")
                        .HasColumnName("Provincia")
                        .HasColumnType("int");

                    b.Property<string>("clave")
                        .IsRequired()
                        .HasColumnName("clave")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnName("usuario")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("UsuarioId");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("Biblioteca.Modelo.Prestamo", b =>
                {
                    b.HasOne("Biblioteca.Modelo.Lector", "lector")
                        .WithMany()
                        .HasForeignKey("Lector")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca.Modelo.Libro", "libro")
                        .WithMany()
                        .HasForeignKey("Libro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca.Modelo.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
